### ISSUE TITLE
Complementary PWM question

### ISSUE THREAD

**Issue by Aequi** [3x8/nostromo#2]
Hi,

First of all I would like to say that your implementation is very clean and readable, thanks for posting such a valuable work. I was searching for a regenerative breaking solution and found your repository. I read the code of motor.c and have a question. Could you please help me with it? 

There is a code for pin initialization for fd6288,
And I am trying to understand the logic of complementary PWM and regenerative brake.

#if defined(FD6288)
  void motorPhaseA(uint8_t hBridgeMode) {
    switch (hBridgeMode) {
      case HBRIDGE_PWM:
        if (!motor.ComplementaryPWM || motor.BrakeActiveProportional) {
          LL_GPIO_SetPinMode(A_FET_LO_GPIO, A_FET_LO_PIN, LL_GPIO_MODE_OUTPUT);
          A_FET_LO_GPIO->BRR = A_FET_LO_PIN;
        } else {
          LL_GPIO_SetPinMode(A_FET_LO_GPIO, A_FET_LO_PIN, LL_GPIO_MODE_ALTERNATE);
        }
        LL_GPIO_SetPinMode(A_FET_HI_GPIO, A_FET_HI_PIN, LL_GPIO_MODE_ALTERNATE);
        break;

It seems that the gate driver pins are not in PWM mode because of this
 if (!motor.ComplementaryPWM || motor.BrakeActiveProportional). If complementary pwm is set on, the brake should be set to full mode, in order to configure the pins in alternate function and generate complementary PWM, but in main.c the motorBrakeFull() function is called which sets che pins as GPIO output. So it looks like the regenerative braking could not be used with fd6288, while it looks OK for ncp3420 drivers.
 
#if defined(NCP3420)
  void motorPhaseA(uint8_t hBridgeMode) {
    switch (hBridgeMode) {
      case HBRIDGE_PWM:
        LL_GPIO_SetPinMode(A_FET_OE_GPIO, A_FET_OE_PIN, LL_GPIO_MODE_OUTPUT);
        A_FET_OE_GPIO->BSRR = A_FET_OE_PIN;
        LL_GPIO_SetPinMode(A_FET_IN_GPIO, A_FET_IN_PIN, LL_GPIO_MODE_ALTERNATE);
        break;
I would be very happy if you could help me understanding the regenerative braking approach and the complementary drive mode.

Sorry for my bad English, it is not my native language.

**Comment by adrianmiriuta** [comment]
@Aequi 

Thx !

Most of the code is forked from:
https://github.com/conuthead/f051bldc
there is also a RC group for discussions 
https://www.rcgroups.com/forums/showthread.php?3322857-A-cheap-32-bit-diy-ESC-and-firmware/

for Technical info see:
http://ww1.microchip.com/downloads/en/devicedoc/regenerative%20braking%20of%20bldc%20motors.pdf
https://hackaday.io/project/3176-gator-quad/log/11741-pwm-control-and-dead-time-insertion


I mainly did the cleanup.

Complementary PWM means Regenerative breaking !

1.  the fd6288 does not need any initialization 
     it's only a HBRIDGE driver
2. motorBrakeFull is only active when the motor is off
3. The complementary PWM is generated by hardware
  motorPwmTimerHandle.Instance = TIM1;
  motorPwmTimerHandle.Init.Prescaler = 0;
  motorPwmTimerHandle.Init.CounterMode = TIM_COUNTERMODE_CENTERALIGNED1;
  motorPwmTimerHandle.Init.Period = TIMER1_INIT_PERIOD;
  motorPwmTimerHandle.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  motorPwmTimerHandle.Init.RepetitionCounter = 0;
  motorPwmTimerHandle.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;

 complementary PWM -> both sides of the HBRIDGE are active driven by PWM
  LL_GPIO_SetPinMode(A_FET_LO_GPIO, A_FET_LO_PIN, LL_GPIO_MODE_ALTERNATE);
  LL_GPIO_SetPinMode(A_FET_HI_GPIO, A_FET_HI_PIN, LL_GPIO_MODE_ALTERNATE);

 freewheeling -> only HI_SIDE is PWM driven  LO_SIDE is fixed
    (not motor.ComplementaryPWM) or  motor.BrakeActiveProportional

    LL_GPIO_SetPinMode(A_FET_LO_GPIO, A_FET_LO_PIN, LL_GPIO_MODE_OUTPUT);
    A_FET_LO_GPIO->BRR = A_FET_LO_PIN;

That's my understanding,
You can ask conuthead, I think his insight is much better !

**Comment by Aequi** [comment]
Thanks for the explanation and references!

Could you please confirm if I got it right.

So the complementary PWM is applied always and when the control input drops from let's say 800 to a lower value like 400 the complementary PWM slows the motor down in the same time regenerating some of the mechanical energy back to the battery. And when we want to simply stop the motor completely it uses the proportional, floating or full break with the corresponding approach.

**Comment by adrianmiriuta** [comment]
@Aequi 
That is my understanding.

**Comment by Aequi** [comment]
Thanks for your help and explanation!
